apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: 7.14.0
  nodeSets:
    - name: default
      count: 1
  http:
    tls:
      selfSignedCertificate:
        disabled: true
