FROM python:3.7

WORKDIR /src

# Setup app user
RUN addgroup --gid 11111 --system app
RUN adduser --shell /bin/false --uid 11111 --ingroup app --system app
RUN chown -R app:app /src

# Install dependencies

RUN pip3 install --upgrade cartography python-dateutil==2.8.0

# Add entrypoint
COPY docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh

USER app
ENTRYPOINT ["/docker-entrypoint.sh"]
