---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: http
  name: yopass-service
spec:
  selector:
    app.kubernetes.io/name: yopass
  type: NodePort
  ports:
    - name: http
      port: 1337
      targetPort: 1337
